function amp(){
	var invisble =  document.getElementById("invisble");
	document.getElementById("invisble").style.display = "block";
	  var amp1 = document.getElementById("damage").value*0.02+2;
	  var amp2 = document.getElementById("damage").value*0.04+4;
	  var amp3 = document.getElementById("damage").value*0.06+6;
	  var amp4 = document.getElementById("damage").value*0.1+8;
	  var amp5 = document.getElementById("damage").value*0.14+10;
	  var amp6 = document.getElementById("damage").value*0.21+12;
	  var amp7 = document.getElementById("damage").value*0.33+14;
	  var amp8 = document.getElementById("damage").value*0.49+16;
	  var amp9 = document.getElementById("damage").value*0.66+18;
	  var amp10 = document.getElementById("damage").value*0.86+20;
	  var amp0 = document.getElementById("damage").value;
	  amp0=amp0*1;
	  amp1=amp1*1;
	  amp2=amp2*1;
	  amp3=amp3*1;
	  amp4=amp4*1;
	  amp5=amp5*1;
	  amp6=amp6*1;
	  amp7=amp7*1;
	  amp8=amp8*1;
	  amp9=amp9*1;
	  amp10=amp10*1;
	  amp1done=amp1+amp0;
	  amp2done=amp2+amp0;
	  amp3done=amp3+amp0;
	  amp4done=amp4+amp0;
	  amp5done=amp5+amp0;
	  amp6done=amp6+amp0;
	  amp7done=amp7+amp0;
	  amp8done=amp8+amp0;
	  amp9done=amp9+amp0;
	  amp10done=amp10+amp0;
      var check1 = document.getElementById("amp1").innerHTML = Math.floor(amp1done);
	  var check2 = document.getElementById("amp2").innerHTML = Math.floor(amp2done);
	  var check3 = document.getElementById("amp3").innerHTML = Math.floor(amp3done);
	  var check4 = document.getElementById("amp4").innerHTML = Math.floor(amp4done);
	  var check5 = document.getElementById("amp5").innerHTML = Math.floor(amp5done);
	  var check6 = document.getElementById("amp6").innerHTML = Math.floor(amp6done);
	  var check7 = document.getElementById("amp7").innerHTML = Math.floor(amp7done);
	  var check8 = document.getElementById("amp8").innerHTML = Math.floor(amp8done);
	  var check9 = document.getElementById("amp9").innerHTML = Math.floor(amp9done);
	  var check10 = document.getElementById("amp10").innerHTML = Math.floor(amp10done);
}